-- 3rd column: Allow for disciplines that might have multiple names 
-- 4th and 5th columns: Disciplines at Sydney University are two separate things - the organisational unit, and the theoretical curriculum unit but they aren't used in practice
-- 6th column: Allows to have a hierarchical tree of disciplines

INSERT INTO lk_discipline VALUES (DEFAULT, '', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Addiction Medicine', 'Drug & Alcohol', 1, 0, 0);
SELECT nextval('lk_discipline_auto_id_seq');
INSERT INTO lk_discipline VALUES (DEFAULT, 'Anatomy', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Biomedical Science', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Dentistry', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Dermatology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Ear, Nose & Throat', NULL, 1, 0, 0);
SELECT nextval('lk_discipline_auto_id_seq');
INSERT INTO lk_discipline VALUES (DEFAULT, 'Ethics', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Experimental Medicine', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'General Practice', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Genetic Medicine', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Imaging', NULL, 1, 0, 0);
SELECT nextval('lk_discipline_auto_id_seq');
INSERT INTO lk_discipline VALUES (DEFAULT, 'Interdisciplinary', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Medicine', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Molecular and Microbial Biosciences', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Ophthalmology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Paediatrics', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Pathology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Obstetrics, Gynaecology and Neonatology', 'Perinatal & Women''s Health', 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Pharmacology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Physiology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Psychiatry', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Public Health', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Rural Health', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Surgery', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Adolescent Health', NULL, 1, 0, 20);
SELECT nextval('lk_discipline_auto_id_seq');
INSERT INTO lk_discipline VALUES (DEFAULT, 'Behavioural Science', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Biochemistry', NULL, 1, 0, 18);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Biostatistics', NULL, 1, 0, 26);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Breast & Endocrine Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Cardiology', 'Cardiovascular Medicine', 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Cardiothoracic Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Clinical Microbiology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Colorectal Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Embryology', NULL, 1, 0, 4);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Endocrinology', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Environmental Health', NULL, 1, 0, 26);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Epidemiology', NULL, 1, 0, 26);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Forensic', NULL, 1, 0, 21);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Gastroenterology', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Geriatric Medicine', '', 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Gynaecology', '', 1, 0, 22);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Haematology', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Head & Neck Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Health Law', NULL, 1, 0, 10);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Hepatology', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Histology', NULL, 1, 0, 4);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Humanities', NULL, 1, 0, 10);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Immunology', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Infectious Diseases', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Molecular Medicine', NULL, 1, 0, 18);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Neonatology', '', 1, 0, 22);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Neurology', 'Neurosciences', 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Neurosurgery', 'Neurosciences', 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Nuclear Medicine', NULL, 1, 0, 14);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Nutrition', NULL, 1, 0, 18);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Obstetrics', '', 1, 0, 22);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Occupational Medicine', NULL, 1, 0, 26);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Oncology', 'Cancer Medicine', 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Orthopaedic Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Palliative Care', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Parasitology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Perinatology', '', 1, 0, 22);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Plastic & Reconstructive Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Preventive Medicine', NULL, 1, 0, 26);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Radiology', NULL, 1, 0, 14);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Rehabilitation Medicine', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Renal Medicine', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Respiratory Medicine', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Rheumatology', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Sexual Health', '', 1, 0, 22);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Sleep Medicine', NULL, 1, 0, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Surgical Oncology', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Upper GI & Hepatobiliary Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Urology', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Vascular Surgery', NULL, 1, 0, 28);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Virology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Women''s Health', '', 1, 0, 22);
SELECT nextval('lk_discipline_auto_id_seq');
INSERT INTO lk_discipline VALUES (DEFAULT, 'Indigenous Health', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Disease Pathogenesis', NULL, 1, 0, 21);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Diagnostic', NULL, 1, 0, 21);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Dental Radiology', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Dental Special Care', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Endodontics', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Fixed Prosthedontics', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Orthodontics', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Paediatric Dentistry', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Periodontics', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Prosthodontics', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Tooth Conservation', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Occlusion', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Oral Surgery', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Implantology', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Population Oral Health', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Dental Biomaterials', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Oral and Maxillofacial Surgery', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Gerodontology', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Oral Medicine', NULL, 1, 1, 6);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Critical Care', NULL, 1, 1, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Anaesthesia', NULL, 1, 1, 104);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Emergency Medicine', NULL, 1, 1, 104);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Intensive Care', NULL, 1, 1, 104);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Acute Surgery', NULL, 1, 0, 104);
INSERT INTO lk_discipline VALUES (DEFAULT, 'OME', NULL, 1, 0, 0);
SELECT nextval('lk_discipline_auto_id_seq');
INSERT INTO lk_discipline VALUES (DEFAULT, 'Microbiology', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Needs Review', NULL, 1, 0, 0);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Disability Studies', NULL, 1, 1, 17);
INSERT INTO lk_discipline VALUES (DEFAULT, 'Evidence Based Medicine', NULL, 1, 0, 26);
