<?php include_once('../application/common/views/_prettyPhotoJsAndCss.phtml'); ?>
<link href="<?php echo $this->baseUrl;?>/css/form.css" media="screen" rel="stylesheet" type="text/css" />
<style type="text/css">
tr.header td {font-style: italic;}
tr.special td {border-top: 1px solid #ff0000; }
span.bname {
  display: block;
  font-size: 12px;
  font-weight: bold;
  margin: 4px 6px 5px 20px;
}
span.biglabel {
  display: block;
  font-size: 20px;
  float: left;
}
td.pname, td.pname_empty{
  border-left: 1px solid #ff0000;
  padding: 0px 5px;
  font-size: 95%;
}
td.pnum, td.pnum_empty {
  border-left: 1px solid #ff0000;
  padding: 0px 5px;
}
td.blockrsc {
  border-left: 1px solid #ff0000;
  padding: 0px 5px;
}
td.user-info {
    border-top:1px solid #ff0000;
    padding: 2px 6px;
}
td a {text-decoration: none ;}
span.bname a img{
    text-decoration: none ;
    border: 1px solid #FFFFFF;
}
.ltlink {
	font-size:90%;
}
/*
Contacts CSS
*/
table#contacts-table {
    border:1px solid #DBDED7;
    padding-left:10px;
    padding-right:10px;
    width: 100%;
}
table#contacts-table .block-td {
    border-right:1px solid #DBDED7;
    vertical-align:top;
    padding-right:10px;
    width:50%;
}
table#contacts-table span.heading {
    font-weight:bold;
    text-decoration:underline;
}
table#contacts-table .casecoordinator-td {
    padding-left:10px;
    vertical-align:top;
    width:50%;
}
table#contacts-table .casecoordinator-td table {
    border-collapse:collapse;
    width:100%;
}
table#contacts-table .casecoordinator-td table td {
    vertical-align:top;
}
table#contacts-table .casecoordinator-td table .pbl-ref {
    font-weight:bold;
    padding-right:10px;
}
table#contacts-table .uid-container {
    padding-top:5px;
    padding-bottom:5px;
}

/* stage css */
.stagecontent {
	background: #FDF5DB;
	padding: 10px;
}
.stagersc {
	padding-left: 5px;
}
.stagetitle {
	font-size: 200%;
}
</style>
<script type="text/javascript">
  $(function() {
	  $('td.pnum, td.pname').hover(function() {
		      $('td.pnum, td.pname', $(this).parent()).css('background-color', '#ffeccf');
		  }, function() {
			  $('td.pnum, td.pname', $(this).parent()).css('background-color', '#FFFFFF');
		  })
  });
</script>
&nbsp;
<table cellspacing="0" cellpadding="0" border="0">
 <tbody>
  <tr class="header">
    <td><?php echo Zend_Registry::get('Zend_Translate')->_('Block') ?></td>
    <td align="center">#</td>
    <td style="padding-left: 2px;">Common name</td>
    <td style="padding-left: 2px;">Clinical name</td>
    <td style="padding-left: 2px;">Resources</td>    
  </tr>
 <?php
 	$sbs = new StageBlockSeqs();
 	$stage_1_last_blok = $sbs->getLastBlockNoForStage("1");
 	$stage_2_last_blok = $sbs->getLastBlockNoForStage("2");
    $num_blocks = count($this->releasedPbls) - 1;

    $resourceViewOrDownloadUrl = $this->url(array('module'=>'default','controller'=>'resource', 'action'=>'viewordownload','type'=>'block'), null, true).'/id/%d/mid/%s/fn/%s';
    foreach($this->releasedPbls as $block => $value) {
    	if (UserAcl::isStaffOrAbove()) {
    		if ($stage_1_last_blok == $num_blocks) {
    			echo "<tr class='stagecontent'><td class='stagetitle'>".Zend_Registry::get('Zend_Translate')->_('Stage')." 1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td class='stagersc'><a href=\"{$this->baseUrl}/guide/proceduralskills/stage/1\">Procedural Skills Handbook</a></td></tr>";
    		} else if ($stage_2_last_blok == $num_blocks) {
    			echo "<tr class='stagecontent'><td class='stagetitle'>".Zend_Registry::get('Zend_Translate')->_('Stage')." 2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td class='stagersc'><a href=\"{$this->baseUrl}/guide/proceduralskills/stage/2\">Procedural Skills Handbook</a></td></tr>";
    		}
    	}
    	$pblsCount = count($value['pbls']);
    	
    	//3 are default (Essential Readings Handbook + Procedural Skills Handbook + Manage Resources)
    	$resources = array();
    	if ($num_blocks != 0) {
	    	$resources[] = "Essential Readings Handbook <span class=\"ltlink\">(<a href=\"{$this->baseUrl}/guide/handbookbypbl/block/{$num_blocks}\" title=\"Handbook ordered by PBL\">By&nbsp;PBL</a>, <a href=\"{$this->baseUrl}/guide/handbook/block/{$num_blocks}\" title=\"Handbook ordered by Name\">By&nbsp;Name</a>)</span><br />";
	    	$resources[] = "<a href=\"{$this->baseUrl}/guide/proceduralskills/block/{$num_blocks}\">Pt-Dr Handbook: Procedural Skills</a><br />";
    	}
        foreach($value['resources'] as $resource) {
            if( $resource['allowUser'] === true) {
                if(isset($resource['customViewUrl']) &&  !empty($resource['customViewUrl'])) {
                    $resources[] = "<a rel=\"prettyPhoto\" href=\"{$resource['customViewUrl']}\">{$resource['title']}</a><br />";
                } else {
                    $filename = base64_encode('Block - '.$num_blocks.' - '.$resource['title']);
                    $resources[] = "<a href=\"".sprintf($resourceViewOrDownloadUrl, $value['blockId'], $resource['mid'], $filename)."\">{$resource['title']}</a><br />";
                }
            }
        }
        //Only Blockchairs and above are allowed to access the link for managestage1or2resources link.
        if(UserAcl::isBlockchairOrAbove()) {
    	   $resources[] = "<a href=\"{$this->baseUrl}/block/managestage1or2resources/ref/{$value['blockId']}\"><b>Manage Resources</b></a>";
        }
        //Only students and certain staff may see the student resources link.
        if(StudentResourceService::showSocialTools()) {
    	   $resources[] = "<a href=\"{$this->baseUrl}/studentresource/compile/block/{$num_blocks}\">All Student Resources</a>";
        }
        $resourcesCount = count($resources);
    	$rowspan = ($pblsCount > $resourcesCount) ? $pblsCount : $resourcesCount; 
    	$pblCoordinators = array($value['pbls'][0][0] => $value['pbls'][0]['pblUids']);
    	$first_pbl_row = array_shift($value['pbls']);
    	$first_resource_row = array_shift($resources);
    	$max_rows = $rowspan -1 ;
    	
        echo "<tr class=\"special\">\n  <td width=\"200\" valign=\"top\" rowspan=\"{$rowspan}\">";
        echo "<span class=\"biglabel\">$num_blocks</span>";
        echo "<span class=\"bname\">$block&nbsp;";
        echo '<a href="javascript:void(0);">';
        echo "<img class=\"helpimg\" onclick=\"javascript:$('#user-info-$num_blocks').toggle();\" title=\"Click to view ".Zend_Registry::get('Zend_Translate')->_('Block')." Chairs\" width='18' src=\"{$this->baseUrl}/img/people.gif\"/>";
        echo "</a></span></td>";
    	echo "<td class=\"pnum\">$first_pbl_row[0]</td>\n  ";
    	echo "<td class=\"pname\"><a href=\"{$this->baseUrl}/pbl/index/ref/{$first_pbl_row[0]}\">$first_pbl_row[1]</a></td>\n  ";
    	echo "<td class=\"pname\"><a href=\"{$this->baseUrl}/pbl/index/ref/{$first_pbl_row[0]}\">$first_pbl_row[2]</a></td>\n";
    	echo "<td class=\"blockrsc\" valign=\"top\">{$first_resource_row}</td>\n";
    	echo "</tr>\n";
    	
        for($x=0; $x<$max_rows; $x++) {
            echo "<tr>\n  ";
            if(isset($value['pbls'][$x])) {
                echo "<td class=\"pnum\">{$value['pbls'][$x][0]}</td>\n  ";
                echo "<td class=\"pname\"><a href=\"{$this->baseUrl}/pbl/index/ref/{$value['pbls'][$x][0]}\">{$value['pbls'][$x][1]}</a></td>\n  ";
                echo "<td class=\"pname\"><a href=\"{$this->baseUrl}/pbl/index/ref/{$value['pbls'][$x][0]}\">{$value['pbls'][$x][2]}</a></td>\n";
                $pblCoordinators[$value['pbls'][$x][0]] = $value['pbls'][$x]['pblUids'];
            } else {
                echo "<td class=\"pnum_empty\">&nbsp;&nbsp;</td>\n  ";
                echo "<td class=\"pname_empty\">&nbsp;&nbsp;</td>\n  ";
                echo "<td class=\"pname_empty\">&nbsp;&nbsp;</td>\n";
            }
            if(isset($resources[$x])) {
                echo "<td class=\"blockrsc\" valign=\"top\">{$resources[$x]}</td>\n";
            } else {
                echo "<td class=\"blockrsc\" valign=\"top\">&nbsp;</td>\n";
            }
            echo "</tr>\n";
        }

        echo '<tr id="user-info-'.$num_blocks.'" style="display:none;">';
        
        ?>
        <td align="left" colspan="5" class="user-info">
        <h3>Contacts</h3>
        <table id="contacts-table">
            <tr>
                <td class="block-td">
                    <?php ##LOOP THROUGH BLOCK CHAIRS UID FOR THIS BLOCK?>
                    <span class="heading"><?php echo Zend_Registry::get('Zend_Translate')->_('Block') ?> Chairs</span><br />
                    <?php if(!empty($value['blockUids'])) :?>
                        <?php $loopCount = 1;?>
                        <?php foreach($value['blockUids'] as $uid) :?>
                            <?php $border = ($loopCount != 1) ? 'border-top:1px solid #DBDED7;' : '';?>
                            <div class="uid-container" style="<?php echo $border;?>"><?php echo Compass::userInfoHtmlOnly($uid);?></div>
                        <?php $loopCount++;?>
                        <?php endforeach; ?>
                    <?php else :?>
                        None Found
                    <?php endif;?>
                </td>
                <td class="casecoordinator-td">
                    <span class="heading">Case Coordinators</span><br />
                    <?php ##LOOP THROUGH CASE COORDINATORS UID FOR EACH PBL REF?>
                    <?php if(!empty($pblCoordinators)) :?>
                        <table>
                            <?php $pblCoordinatorsLoopCount = 1;?>
                            <?php foreach($pblCoordinators as $key => $uids) :?>
                            <?php $pblCoordinatorBorder = ($pblCoordinatorsLoopCount != 1) ? 'border-top:1px solid #DBDED7;' : '';?>
                            <tr style="<?php echo $pblCoordinatorBorder;?>">
                                <td class="pbl-ref"><?php echo $key?></td>
                                <td>
                                    <?php if(count($uids) > 0) :?>
                                        <?php $loopCount = 1;?>
                                        <?php foreach($uids as $uid) :?>
                                            <?php $border = ($loopCount != 1) ? 'border-top:1px solid #DBDED7;' : '';?>
                                            <div class="uid-container" style="<?php echo $border;?>">
                                                <?php echo Compass::userInfoHtmlOnly($uid);?>
                                            </div>
                                            <?php $loopCount++;?>
                                        <?php endforeach; ?>
                                    <?php else:?>
                                    None Found
                                    <?php endif;?>                                        
                                </td>
                            </tr>
                            <?php $pblCoordinatorsLoopCount++;?>
                            <?php endforeach; ?>
                        </table>                           
                    <?php else :?>
                        None Found
                    <?php endif;?>

                </td>
            </tr>
        </table>
        <br />
        </td>          
        <?php
        echo '</tr>';
        
        $num_blocks--;
    }
 ?>
  </tbody>
</table>
