<style type="text/css">
.user{ border: solid 1px #bbbbbb; background-color: #eeeeee;}
.horizontal1 {float: left; margin: 4px; width: 80px; }
.horizontal2 {float: left; margin: 4px; width: 200px; text-align: center; }
.horizontal3 {float: left; margin: 4px; width: 200px; padding-left: 50px; }
.deleteimg {border: 0px; padding-left:16px; }
</style>
<link href="<?php echo $this->baseUrl;?>/css/impromptu.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery/jquery-impromptu.2.2.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/removeuser.js"></script>
<?php if (count($this->domainadmins) > 0) :?>
<table>
  <thead><tr align="left"><th><div class="horizontal1">Delete</div><div class="horizontal2">Domain</div><div class="horizontal3">Domain Administrator</div></th></tr></thead>
  <tbody>
<?php foreach ($this->domainadmins as $domainadmin): ?>
  <tr class="user" id="userid<?php echo $domainadmin['id'] ?>">
    <td>
      <div class="horizontal1"><a href="javascript:;" onclick="removeUser('deletedomainadmin', <?php echo $domainadmin['id']?>, '<?php echo $domainadmin['uid']?>');"><img src="<?php echo $this->baseUrl;?>/img/delete.gif" class="deleteimg"></a></div>
      <div class="horizontal2"><?php echo $domainadmin['name']?></div>
      <div class="horizontal3"><span class="userid"><?php echo $this->escape($domainadmin['uid']) ?></span><div class="userdetail"></div></div>
    </td>
  </tr>
<?php endforeach; ?>
  </tbody>
</table>
<?php else : ?>
<p>No domain administrator found.</p>
<?php endif; ?>
<p><a href="<?php echo $this->url(array('action' => 'adddomainadmin', 'controller' => 'admin'), null, true); ?>">Add Domain Administrator</a></p>