<div>
  <h2>Deleting linkage</h2>
  <p>Are you sure you want to approve the deletion of linkage between teaching activity <?php echo $this->ta_id ?>
  and learning objective <?php echo $this->lo_id ?>?<p>
  <form method="post">
    <p><input type="radio" name="sure" value="yes" /> Yes
    <input type="radio" name="sure" value="no" checked="checked" /> No&nbsp;&nbsp;&nbsp;
    <input type="submit" value="Submit" id="submit"/></p>
  </form>
</div>