<?php 
$loggedIn = Zend_Auth::getInstance()->hasIdentity(); 
$qqHref = $this->url(array('module'=>'default','controller'=>'search','action'=>'index','searchtype'=>'qq'));
$myDetailsHref = $this->url(array('module'=>'disc','controller'=>'disc','action'=>'mydetails'));
?>

<link href="<?php echo $this->baseUrl; ?>/css/home.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl;?>/css/form.css" media="screen" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl; ?>/js/jquery/jquery.tooltip.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".helpimg").tooltip({
            track: true,
            delay: 0,
            showURL: false,
            opacity: 1,
            showBody: " - ",
            left: 0
        });
    });
</script>
<div id="homeContainer">
    <h1 class="centerText"><?php echo $this->escape($this->title);?></h1>
    <div id="mainText">
        <p class="info">
            <img class="mainImage" src="<?php echo $this->baseUrl;?>/img/Stanley_compass.jpg" width="300" alt=""/>
            Compass is your key to the <?php echo Utilities::getCopyrightUni(); ?> Medical curriculum.<br /><br />
            Compass enables <b>students</b> to find out what they should learn, and when, where and how it will be taught.<br /><br />
            Compass allows <b>teachers</b> to find out what their students already know and what they will learn later, and also enables them to submit new learning objectives.<br /><br />
            Compass enables <b>course coordinators and administrative staff</b> to efficiently schedule teaching activities and manage educational resources.
        </p>
        <?php if (! $loggedIn): ?>
        <p>
            <span class="clickHere">Click here to <a href="<?php echo $this->url(array('module'=>'default','controller'=>'auth','action'=>'login'),null,true); ?>">log in</a></span>
        </p>
        <?php endif; ?>
    </div>
    <?php if($loggedIn): ?>
    <br />
    <form action="<?php echo $qqHref; ?>" method="post" name="searchMyLo" id="searchMyLo">
        <?php echo $this->formHidden('context','lo',array('style'=>'')); ?>
        <?php echo $this->formHidden('process','staff|1',array('style'=>''));?>
    </form>
    <form action="<?php echo $qqHref; ?>" method="post" name="searchMyTa" id="searchMyTa">
        <?php echo $this->formHidden('context','ta',array('style'=>'')); ?>
        <?php echo $this->formHidden('process','staff|2',array('style'=>''));?>
    </form>
    <div>
        <a href="javascript:document.searchMyTa.submit();" class="helpimg boldText" title="My Teaching Activities - Search teaching activities belonging to you.">My Teaching Activities</a>&nbsp;&nbsp;
        <a href="javascript:document.searchMyLo.submit();" class="helpimg boldText" title="My Learning Objectives - Search learning objectives belonging to you.">My Learning Objectives</a>&nbsp;&nbsp;
        <a href="<?php echo $myDetailsHref; ?>" class="helpimg boldText" title="My Details - View 'My Details' section of my disciplines.">My Details</a>&nbsp;&nbsp;
    </div>
    <?php endif;?>
</div>
