
<?php $customSortOrder = '[0,0]'; ?>
<?php $highlightSearchTable = true; ?>
<?php include_once('../application/common/views/_tableSortJsAndCss.phtml'); ?>
<?php include_once('../application/common/views/_listOfDisciplinesJsAndCss.phtml'); ?>

<script src="<?php echo $this->baseUrl;?>/js/jquery/jquery-impromptu.2.2.min.js" type="text/javascript"></script>
<link href="<?php echo $this->baseUrl;?>/css/form.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl;?>/css/advancedSearchPrint.css" media="print" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl;?>/css/advancedSearchScreen.css" media="screen" rel="stylesheet" type="text/css" />
<?php if( $this->process == 'advanced' || $this->process == 'simple'):?>
    <?php include_once('searchSimpleAdvancedJsCss.phtml'); ?>
<?php endif;?>

<?php if($this->searchType == 'qq'): ?>
    <?php if($this->quickQueriesProcessed != true) :?>
        <link href="<?php echo $this->baseUrl;?>/css/quickQueries.css" media="screen" rel="stylesheet" type="text/css" />
        <?php include_once('captureForm.phtml');?>
        <?php include_once('captureQuickQueriesForm.phtml');?>
        <?php include_once('templates/quickQueriesSearchForm.phtml');?>
    <?php endif;?>
<?php else :?>
	<?php //Check if $this->searchType exists or not !?>
	<?php if(in_array($this->searchType, array_keys(SearchConstants::$config['view']))):?>
    <div id="searchForm">
    <h1 id='title'><?php if ($this->process == 'simple'):?>Search<?php else :?>Advanced Search<?php endif;?></h1>
        <form name="search" method="get" action="<?php echo $this->url(array('module'=>'default','controller'=>'search','action'=>'index','searchtype'=>$this->searchType),null,true);?>">
        <table id='searchTable'>
            <?php include_once('captureForm.phtml');?>
            <?php include_once('templates/'.$this->searchType.'SearchForm.phtml'); ?>
            <tr>
                <td>&nbsp;</td>
                <td colspan="4">
                    <input type='hidden' id='process' name='process' value='<?php echo $this->process;?>' />
                    <input type="submit" accesskey="S" id="submit" name="submit" value="Search"/>
                    <input type="button" accessKey="R" id="reset" onclick="javascript:resetSearch();" value="Reset"/>
                    <?php echo $this->placeholder('displayQueryLink'); ?>
                </td>
            </tr>
        </table>
    </div>
    </form>
    <?php else :?>
    	<?php unset($this->displayresult);?>
    	<div class="red" style="font-size:150%">Error!</div>
    <?php endif ;?>
<?php endif;?>
<?php include_once('searchResults.phtml'); ?>
