<?php if (isset($this->displayresult)) : ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery/jquery.thickbox.min.js"></script>
    <link rel="stylesheet" href="<?php echo $this->baseUrl;?>/css/jquery.thickbox.css" type="text/css" media="screen" />
    <link href="<?php echo $this->baseUrl;?>/css/tableInner.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl;?>/css/impromptu.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->baseUrl;?>/css/recordings.css"  media="screen" rel="stylesheet" type="text/css" />
    
    <?php include_once('../application/common/views/_prettyPhotoJsAndCss.phtml'); ?>
        
    <?php //Throw alert for search results which fetched more then 600 records?>
    <?php if(count($this->results['context']) > 600) :?>
    <script type="text/javascript"> 
        var alertTooManyRecords = "Your query fetched <?php echo count($this->results['context'])?> records which can take longer to process.\n\nInternet Explorer Users: Please click 'NO' to abort script.\n\nOther Users: Please click 'CONTINUE'.";
        alert(alertTooManyRecords);
    </script>  
    <?php endif; ?>

    <?php if($this->process == 'objective' || $this->process == 'activity'):?>
    <script src="<?php echo $this->baseUrl;?>/js/addNewLink.js" type="text/javascript"></script>
    <?php endif;?>

    <?php if(count($this->results['context'])) : ?>
    <div id="resultPrintContainer">
        <div id="resultContainer">
            <span id='resultCount'><?php echo count($this->results['context']);?></span> result<?php echo count($this->results['context']) > 1 ? 's':'' ?> found.
        </div>
        <div id="printContainer">
            <?php if($this->searchType != 'qq'): ?>
            
            <a href="#TB_inline?width=500&height=430&inlineId=hiddenModalContent" title="Configure Search Results" class="thickbox">Configure</a>&nbsp;&nbsp;&nbsp;
            <a href="#TB_inline?width=500&height=430&inlineId=podcast-container" title="Configure Podcast" class="thickbox">Podcast</a>&nbsp;&nbsp;&nbsp;            
            
            <?php endif;?>
            <a href="<?php echo str_replace($this->baseUrl.'/htdocs',$this->baseUrl,$this->url).'&format=csv'; ?>" title="Click to download SEARCH RESULTS as CSV">Download CSV</a>&nbsp;&nbsp;&nbsp;
            <a href="#" title="Click to PRINT" onclick="window.print()">Print</a>
        </div>
    </div>
    <br />
    <?php $customNoOfColumns = count($this->columns['column']); ?>
    <table class="tableSorter">
        <?php $paginationBg = 'top';?>
        <?php include('../application/common/views/_footerPagination.phtml'); ?>
    </table>
    <table id="sortTable" class="tableSorter">
      <thead>
        <tr>
          <?php foreach($this->columns['column'] as $id=>$name):?>
                <th><?php echo $name;?></th>
          <?php endforeach;?>
        </tr>
      </thead>
      <?php try {
                include_once('_searchResultRows.phtml') ;
            } catch(Exception $ex){
                echo 'Error !';
            }
      ?>
      <?php $paginationBg = 'bottom';?> 
      <?php include('../application/common/views/_footerPagination.phtml'); ?>
    </table>
    <?php if($this->searchType != 'qq'): ?>
        <?php include_once('_configureSearchResults.phtml') ;?>
        <?php include_once('_configurePodcast.phtml') ;?>
    <?php endif;?>
   <?php else : ?>
      <p><b>No results found.</b></p>
   <?php endif; ?>
   
<?php endif; ?>
