<?php echo $this->doctype('XHTML1_TRANSITIONAL'); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head profile="http://www.w3.org/2005/10/profile">
        <link rel="shortcut icon" href="<?php echo $this->baseUrl;?>/img/favicon.ico" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--[if lt IE 8]>
<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE8.js"></script>
<![endif]-->
        <link href="<?php echo $this->baseUrl;?>/css/site.css" media="all" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl;?>/css/menu.css" media="all" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/jquery_1_4_2.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/main.js"></script>
        <title><?php
            $title = strip_tags($this->headTitle()->__toString());
            echo substr($title, 0, strpos($title, PageTitle::TITLE_DELIMITER)); 
        ?></title>
        <script type="text/javascript">
            var BASE_URL = '<?php echo $this->baseUrl;?>';
        </script>
    </head>
    <body>
    <?php echo $this->partial("_header.phtml"); ?>

    <div id="container">
        <div id="content" class="column"><div id="pad">

            <?php echo $this->layout()->content; ?>

        </div></div>
    </div>
    <?php echo $this->partial("_jqueryAjaxLoader.phtml"); ?>
    <?php echo $this->partial("_footer.phtml"); ?>
    </body>
</html>
