
<link href="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/themes/custom-theme/jquery.ui.all.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/ui/jquery.ui.core.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/ui/jquery.ui.widget.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/ui/jquery.ui.tabs.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/ui/jquery.ui.mouse.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/ui/jquery.ui.sortable.min.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/ui/jquery.ui.datepicker.min.js"></script>
<?php
/*
 * KEEP ON ADDING MORE UI STUFF AS NEEDED. 
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery_1_4_2/ui/jquery.ui.button.min.js"></script>
*/
?>


