<link href="<?php echo $this->baseUrl;?>/css/jquery/jquery.fancybox.css"   media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery/jquery.fancybox-1.2.1.pack.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/resourcesubmission.js"></script>