<?php 
    $onLoadSortOrder = '[0,0]';
    $url = Compass::request();
    
    $cookieName = 'TABLESORTER_'.$url['module'].'_'.$url['controller'].'_'.$url['action'];
    $cookieName.= (strlen($url['searchType']) > 0) ? '_'.$url['searchType'] : '';
    $cookieName.= (strlen($url['context']) > 0) ? '_'.$url['context'] : '';
    $cookieName = strtoupper($cookieName);

    if (isset($cookieName) && isset($_COOKIE[$cookieName]) && strlen(trim($_COOKIE[$cookieName])) > 0){
        $onLoadSortOrder = $_COOKIE[$cookieName];
    }else if(isset($customSortOrder) && strlen($customSortOrder) > 0) {
        $onLoadSortOrder = $customSortOrder;
    }
    
?>

<?php if(isset($cookieName)) :?>
    <script type="text/javascript">
        var cookieSearchSortOrder = '<?php echo $cookieName;?>';
    </script>
<?php endif;?>

<!--  Table Sort JS And CSS : START -->
<script src="<?php echo $this->baseUrl;?>/js/jquery/jquery.cookie.min.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/js/jquery/jquery.hotkeys-0.7.8-packed.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/js/jquery/jquery.tablesorter.compass.js" type="text/javascript"></script>
<?php if(isset($highlightSearchTable)):?>
<script src="<?php echo $this->baseUrl;?>/js/jquery/jquery.tablesorter.highlight.searchTable.js" type="text/javascript"></script>
<?php else :?>
<script src="<?php echo $this->baseUrl;?>/js/jquery/jquery.tablesorter.highlight.js" type="text/javascript"></script>
<?php endif;?>
<script src="<?php echo $this->baseUrl;?>/js/jquery/jquery.tablesorter.pager.min.js" type="text/javascript"></script>
<script type="text/javascript">
    //Create table sorter and table pagination
    $(document).ready(function() {
    	$("#submit").click(function(){
    	    $.cookie(cookieSearchPage, null, { path: '/'}); 
    	});
    	$("div.quickQuery a").click(function(){
    		$.cookie(cookieSearchPage, null, { path: '/'}); 
        });
        $("#sortTable")
            .tablesorter({
                          widthFixed: true, 
                          sortList: [<?php echo $onLoadSortOrder; ?>], 
                          textExtraction: function(node) { 
                              if(typeof node.getElementsByTagName('table')[0] != 'undefined') {
                            	    return '';
                              } else if(typeof node.getElementsByTagName('a')[0] != 'undefined') {
                                  v = node.getElementsByTagName('a')[0].innerHTML;
                                  return v.substr(0, 150);
                              } else {
                                  v = node.innerHTML;
                                  return v.substr(0, 150);
                              }
                          }, 
                          widgets: ['zebra', 'columnHighlight']
                          <?php if(isset($this->columns['column']) && count($this->columns['column']) > 0 
                                && isset($this->columns['subColumn']) && count($this->columns['subColumn']) > 0) :?>
                          ,headers: {<?php echo count($this->columns['column'])-1;?>:{sorter: false}}
                          <?php endif;?>
            })
            .tablesorterPager({
                          container: $(".pagerOne"),
                          positionFixed:false
            });
    }); 
</script>

<link href="<?php echo $this->baseUrl;?>/css/table.css" media="screen" rel="stylesheet" type="text/css" />
<!--  Table Sort JS And CSS : END -->

