<style>
body {min-width:600px; width: 625px}
</style>

<?php echo $this->render('teachingactivity/view/_jsCss.phtml')?>
<div id="tacontainer" style="width:615px; min-height:370px; padding:5px">
  <?php // Added class 'eventsResources' to remove 360px right margin ?>
  <div id="talos" class="eventsResources">
    <?php echo $this->render('teachingactivity/view/_learningobjectives.phtml')?>
  </div>
  <div id="tapadding"></div>
</div>
