<script src="<?php echo Compass::baseUrl();?>/js/jquery/jquery.tablesorter.min.js"          type="text/javascript"></script>
<script src="<?php echo Compass::baseUrl();?>/js/jquery/jquery.tablesorter.highlight.js"    type="text/javascript"></script>
<link href="<?php echo Compass::baseUrl();?>/css/table.css" media="screen" rel="stylesheet" type="text/css" />

<?php 
$sortableId = 'table.tableSorter';
if(property_exists($this,'customSortableId') && $this->customSortableId != null) {
    $sortableId = $this->customSortableId;
}
?>
<script type="text/javascript">
    $(document).ready(function() {
        $("<?php echo $sortableId;?>").tablesorter({sortList: [[0,0]],widgets: ['zebra', 'columnHighlight'],headers: {0: {sorter: 'digit'}}});
    }); 
</script>
