<?php echo $this->render('people/view/_jsCss.phtml')?>
<?php include_once('../application/common/views/_prettyPhotoJsAndCss.phtml'); ?>
<div id="tacontainer">
  <div id="tatop">
	<h2><?php  echo $this->persontype." profile: "; ?><?php echo $this->person['cn'][0] ?></h2>
  </div>
  
  <div id="tametadata">
      <?php echo $this->render('people/view/_details.phtml')?>
      <?php echo $this->render('people/view/_photos.phtml')?>
      
      <?php echo $this->render('people/view/_groups.phtml')?>
  </div>
  
  <div id="tacontent">
  	<div>
  	<?php if($this->socialtools):?>
  	    <div style="position: relative; width: 100%; height: 28px;">
    	<div style="position: absolute; left: 0; "><h3 style="margin-top: 0px;margin-bottom: 0px">
    	<?php if($this->studentresourcesortorder=='date'): ?>Recently uploaded resources<?php else: ?>Top rated resources<?php endif; ?>
    	</h3>
    	</div>
    	<div style="position: absolute; right: 0px; top: 5px;font-size:smaller">
		    <span>Sort by:
		    <?php if($this->studentresourcesortorder=='date'): ?><a href="<?php echo $this->url(array('module'=>'default','controller'=>'people', 'action'=>'view', 'uid'=>$this->person['uid'][0]),'default',true); ?>/sortby/rating"><?php endif; ?>rating<?php if($this->studentresourcesortorder=='date'): ?></a><?php endif; ?>
			|
		    <?php if($this->studentresourcesortorder!='date'): ?><a href="<?php echo $this->url(array('module'=>'default','controller'=>'people', 'action'=>'view', 'uid'=>$this->person['uid'][0]),'default',true); ?>/sortby/date"><?php endif; ?>date<?php if($this->studentresourcesortorder!='date'): ?></a><?php endif; ?>
		   </span>
		</div>
	</div>
  	<?php echo $this->render('studentresource/studentresourcelarge.phtml')?>
  	<?php endif;?>
	</div>
  </div>
  <div id="tapadding"></div>
</div>