<?php if (UserAcl::isStaffOrAbove()) :?>
<div id="stagelinks">
    <?php if ($this->pblRef == $this->stage1pbl) :?>
        <a href="<?php echo $this->baseUrl;?>/pbl/display/type/lo/ref/<?php echo $this->stage1pbl?>" class="active"><?php echo Zend_Registry::get('Zend_Translate')->_('Stage') ?> 1</a>
    <?php else : ?>
        <a href="<?php echo $this->baseUrl;?>/pbl/display/type/lo/ref/<?php echo $this->stage1pbl?>"><?php echo Zend_Registry::get('Zend_Translate')->_('Stage') ?> 1</a>
    <?php endif; ?>
    <?php if ($this->pblRef == $this->stage2pbl) :?>
        <a href="<?php echo $this->baseUrl;?>/pbl/display/type/lo/ref/<?php echo $this->stage2pbl?>" class="active"><?php echo Zend_Registry::get('Zend_Translate')->_('Stage') ?> 2</a>
    <?php else : ?>
        <a href="<?php echo $this->baseUrl;?>/pbl/display/type/lo/ref/<?php echo $this->stage2pbl?>"><?php echo Zend_Registry::get('Zend_Translate')->_('Stage') ?> 2</a>
    <?php endif; ?>
</div>
<?php endif; ?>
