<link href="/compass/css/form.css" media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl;?>/css/tableNoSort.css" media="screen" rel="stylesheet" type="text/css" />
<?php $href = $this->url(array('module'=>'default','controller'=> 'learningobjective', 'action'=>'view')); ?>
<div>
  <h2>Archiving learning objective <?php echo $this->lo->auto_id; ?></h2>
  <p>Are you sure you want to archive this learning objective?<p>
  <p>If you do, linkage from this learning objective to the following teaching activity(ies) will be archived.<p>
  <?php $taFinder = new TeachingActivities();?>
  <ul>
  <?php foreach ($this->linkedtas as $ta) :?>
    <?php $row = $taFinder->fetchRow("auto_id={$ta['auto_id']}")?>
    <li>Teaching activity <?php echo $ta['auto_id'] ?><br/>
    - <b>Type:</b> <?php echo $this->escape($row->type) ?> <b>Name:</b> <?php echo $this->escape($row->name) ?>.<br/>
    - <b>Problem:</b> <?php echo $this->escape($row->pbl) ?>
    <b>Block:</b> <?php echo $this->escape($row->block) ?>
    <b>Stage:</b><?php echo $this->escape($row->stage) ?></li>
  <?php endforeach; ?>
  </ul>
  <br/>
  <form method="post">
    <p><input type="radio" name="sure" value="yes" /> Yes
    <input type="radio" name="sure" value="no" checked="checked" /> No&nbsp;&nbsp;&nbsp;
    <input type="submit" value="Submit" id="submit"/></p>
  </form>
</div>