<link href="<?php echo $this->baseUrl;?>/css/tableNoSort.css"   		media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl;?>/css/lotaview.css"        		media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl;?>/css/form.css"          		media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl;?>/css/impromptu.css"     		media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/jquery/jquery-impromptu.2.7.min.js"></script>
<?php include_once('../application/common/views/_prettyPhotoJsAndCss.phtml'); ?>
<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/lotaview.js"></script>
<?php include_once('../application/common/views/_sort.phtml'); ?>
&nbsp;
<table>
    <tr>
        <td class="loViewContainerLeft"><?php include_once('view/view_left.phtml');?></td>
        <td class="loViewContainerRight"><?php include_once('view/view_right.phtml');?></td>
    </tr>
</table>
