INSERT INTO lk_theme VALUES(DEFAULT, '', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Practice - Evidence-based medical practice', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Practice - Effective team building and team spirit', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Practice - Leadership and management skills', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Managing common medical problems', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Dealing with common emergency medical problems', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Diagnosis of life threatening medical conditions', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Effective doctor patient communication', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Clinical reasoning and decision making', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Bio-medical vs. biopsychosocial approach to clinical encounter', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - History taking and physical exam skills', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Diagnosis skills', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Malpractice and patient safety', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Patient management and investigating', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Prescribing skills', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Basic clinical procedures', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Patient - Patient education', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Community - Population health and health system in Saudi Arabia', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Community - Orientation to health services/providers in the community', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and the Community - Health promotion and disease control in the community', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Professionalism - Professional behaviour of medical doctor', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Professionalism - Different roles and responsibilities of a medical professional', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Professionalism - Patient safety', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Professionalism - Professional development and personal growth', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Professionalism - Common ethical problems and concerns in medicine', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Professionalism - Quality focus practice (maintenance and development of quality)', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Research - Introduction to medical research', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Research - Writing research proposal', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Research - Conducting medical research', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Information Technology - Uses of IT in health profession', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Information Technology - Practical application of IT in medicine', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Communication Skills - The basics of communication skills', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Communication Skills - The impact of communication on patient safety', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Communication Skills - Communication with difficult patient/person', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Communication Skills - Communication via different tools', '');
INSERT INTO lk_theme VALUES(DEFAULT, 'Doctor and Communication Skills - Breaking bad news', '');
