<div id="edithistory" class="rhsbox">
	<h3 class="rhsheading">Edit History</h3>
	<div class="mcontent">
	<?php if (count($this->revisions)):?>
		<table id="edittable" width="100%">
    		<tr><th>#</th><th>Created By</th><th>Date</th></tr>
		<?php foreach ($this->revisions as $revision) : ?>
			<tr align="center"<?php echo ($this->ta->version == $revision->version) ? 'class="currentversion"' : '' ?>>
				<td><a href="<?php echo $this->url(array('module'=>'default','controller'=>'teachingactivity','action'=>'view','id'=>$revision->auto_id, 'latest'=>'f'),null,true); ?>">
					<?php echo $revision->version; ?></a></td>
				<td><?php echo $this->escape(UserService::getUidFullNameOnly($revision->created_by)) ?></td>
				<td><?php echo $this->displayDate($revision->date_created); ?></td>
			</tr>
		<?php endforeach; ?>
		</table>
	<?php else: ?>
		<p>None</p>
	<?php endif; ?>
	</div>
</div>