<script type="text/javascript" src="<?php echo $this->baseUrl;?>/js/audience.js"></script>
<script type="text/javascript">
    $(function() {
    	//$('#ownertable').css('margin-left', '10px').css('margin-right', '10px');
        $('#ownertable').css('border', '1px solid #ffe0af').css('border-collapse', 'collapse');
        
    });
</script>

<div>
  <div class="subHeadings subHeadingsResources">Owner and Audience</div>
  <table id="ownertable" width="100%" border="1" cellspacing="0">
	<tr><th width="100px">Owner:</th>		<td><?php echo $this->lo->owner; ?></td></tr>
	<tr><th valign="top">Audience:</th>
		<td><form>
		<?php
			$identity = Zend_Auth::getInstance()->getIdentity();
			$owner = $this->lo->owner;
			$currAudience = $this->lo->audience_arr;
			$domainFinder = new Domains();
			$allAudience = $domainFinder->getAllNames('auto_id ASC');
			foreach ($allAudience as $k => $audience) {
				$checked = (in_array($audience, $currAudience)) ? ' checked="checked"' : '';
				if ($owner === $audience) {
					echo "<input type=\"checkbox\" disabled=\"disabled\"{$checked}>{$audience}<br />";
				} else if ($audience === $identity->domain) {
					echo "<input type=\"checkbox\"{$checked} id=\"domaindamincheckbox\" onclick=\"addremoveaudience('lo', {$this->lo->auto_id}, $k, '{$audience}');\">{$audience}<br />";
				} else {
					echo "<input type=\"checkbox\" disabled=\"disabled\"{$checked}>{$audience}<br />";
				}
			}
		?>
		</form></td>
	</tr>
</table>
</div>
<?php ?>
