<h3>Manage Lists</h3>
<ul>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/Themes">Themes</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/Reviews">Curriculum Reviews</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/GradAttribs">Graduate Attributes</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/LOScopes">Learning Objective Scopes</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/LOVerbs">Learning Objective Verbs</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/ActivityTypes">Activity Types</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/AssessTypes">Assessment Types</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/Jmos">JMO Attributes</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/Skills">Skills</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/Stages">Stages</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/Systems">Systems</a></li>
	<li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/Terms">Terms</a></li>
	
    <li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/StaffPage">Staff Pages</a></li>
    <li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/StaffType">Staff Types</a></li>
    <li><a href="<?php echo $this->baseUrl ;?>/admin/editlk/lk/PblRooms">PBL Rooms</a></li>
    
</ul>
